# server.port =  80
#   server.servlet.context-path= /springboot_study
#
#   spring.datasource.url=jdbc:mysql://localhost:3306/springboot_study?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
#   spring.datasource.username=root
#   spring.datasource.password=123456
#   spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#   spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
#   #thymeleaf 配置
#   spring.thymeleaf.mode=HTML5
#   spring.thymeleaf.encoding=UTF-8
#   spring.thymeleaf.servlet.content-type=text/html
#   #缓存设置为false, 这样修改之后马上生效，便于调试
#   spring.thymeleaf.cache=false
#   #mybatis-plus
#   mybatis-plus.mapper-locations=classpath:mapper/*.xml
# #下划线转java驼峰命名
# mybatis-plus.configuration.map-underscore-to-camel-case: true
#   #控制台打印sql语句
#   mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#   #log4j2日志
#   logging.config=classpath:log4j2.xml
#   logging.level.com.example.springboot=debug
#
#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp

server:
  #访问端口号
  port: 80
  servlet:
    #访问项目名称
    context-path: /springboot_study

spring:
  #数据库设置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_study?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #模板设置
  thymeleaf:
    mode: HTML5
    #编码格式
    encoding: UTF-8
    #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false
    servlet:
      content-type: text/html
#mybatis-plus设置
mybatis-plus:
  #mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #下划线转java驼峰命名
    map-underscore-to-camel-case: true
    #控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#loggin日志打印
logging:
  config: classpath:log4j2.xml
