server:
  #访问端口号
  port: 80
  servlet:
    #访问项目名称
    context-path: /springboot_study

spring:
  #数据库设置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_study?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #模板设置
  thymeleaf:
    mode: HTML5
    #编码格式
    encoding: UTF-8
    #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false
    servlet:
      content-type: text/html
#mybatis-plus设置
mybatis-plus:
  #mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #下划线转java驼峰命名
    map-underscore-to-camel-case: true
    #控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#loggin日志打印
logging:
  config: classpath:log4j2.xml
